# Generated by Django 2.2 on 2019-06-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='telp',
            field=models.TextField(default='0812', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='waktu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
