# Generated by Django 2.2 on 2019-07-03 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0002_auto_20190627_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='pembeli',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='telp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='waktu',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
