# Generated by Django 2.2 on 2019-07-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0003_auto_20190703_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='barang',
        ),
        migrations.DeleteModel(
            name='DaftarBarang',
        ),
        migrations.DeleteModel(
            name='Transaksi',
        ),
    ]
