# Generated by Django 2.2 on 2019-07-18 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0005_barang_kasir_pesan_transaksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='dibayar',
            field=models.CharField(default='Nan', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaksi',
            name='disetujui',
            field=models.CharField(default='Nan', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='waktu',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 21, 9, 22, 859138)),
        ),
    ]
