# Generated by Django 2.2 on 2019-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbarang',
            name='jumlah',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listbarang',
            name='waktu',
            field=models.TimeField(auto_now=True),
        ),
    ]
