# Generated by Django 2.2 on 2019-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0003_auto_20190618_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listbarang',
            name='waktu',
            field=models.DateTimeField(),
        ),
    ]
