# Generated by Django 2.2 on 2019-06-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0005_auto_20190618_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbarang',
            name='waktu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
